package com.storemesh.android

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.grid.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import coil.compose.AsyncImage
import kotlinx.coroutines.launch

private enum class ShopTab { Home, Orders, Cart, Profile }

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ShopScreen(accessToken: String, onLogout: () -> Unit) {
    val scope = rememberCoroutineScope(); val drawer = rememberDrawerState(DrawerValue.Closed); val snackbars = remember { SnackbarHostState() }
    var tab by remember { mutableStateOf(ShopTab.Home) }; var products by remember { mutableStateOf<List<Product>>(emptyList()) }; var cart by remember { mutableStateOf<List<CartLine>>(emptyList()) }; var query by remember { mutableStateOf("") }; var selected by remember { mutableStateOf<Product?>(null) }; var showCheckout by remember { mutableStateOf(false) }; var loading by remember { mutableStateOf(true) }
    LaunchedEffect(accessToken) { loading = true; runCatching { GraphQLClient().products(accessToken) }.onSuccess { products = it }.onFailure { snackbars.showSnackbar("Could not load products") }; runCatching { GraphQLClient().cart(accessToken) }.onSuccess { cart = it }; loading = false }
    fun updateCart(productId: String, delta: Int) { val next = cart.map { if (it.productId == productId) it.copy(quantity = it.quantity + delta) else it }.filter { it.quantity > 0 }.toMutableList(); if (next.none { it.productId == productId } && delta > 0) next.add(CartLine(productId, delta)); scope.launch { runCatching { StoreMeshApi().saveCart(accessToken, next) }.onSuccess { cart = it }.onFailure { snackbars.showSnackbar("Unable to save cart") } } }
    ModalNavigationDrawer(drawerState = drawer, drawerContent = { ModalDrawerSheet { Column(Modifier.padding(24.dp)) { Text("StoreMesh", style = MaterialTheme.typography.headlineSmall, fontWeight = FontWeight.Bold, color = MaterialTheme.colorScheme.primary); Text("Shop smarter. Live better.", color = MaterialTheme.colorScheme.onSurfaceVariant); Spacer(Modifier.height(24.dp)); listOf("Home" to ShopTab.Home, "Orders" to ShopTab.Orders, "Cart" to ShopTab.Cart, "Profile" to ShopTab.Profile).forEach { (label, target) -> NavigationDrawerItem(label = { Text(label) }, selected = tab == target, onClick = { tab = target; scope.launch { drawer.close() } }, icon = { Icon(Icons.Default.Home, null) }) }; Spacer(Modifier.weight(1f)); TextButton(onClick = onLogout, modifier = Modifier.fillMaxWidth()) { Text("Sign out", color = MaterialTheme.colorScheme.error) } } } }) {
        Scaffold(topBar = { TopAppBar(title = { Text(when (tab) { ShopTab.Home -> "StoreMesh"; ShopTab.Orders -> "Orders"; ShopTab.Cart -> "Your cart"; ShopTab.Profile -> "Profile" }, fontWeight = FontWeight.Bold) }, navigationIcon = { IconButton({ scope.launch { drawer.open() } }) { Icon(Icons.Default.Menu, "Open menu") } }, actions = { IconButton({ tab = ShopTab.Cart }) { BadgedBox({ if (cart.sumOf { it.quantity } > 0) Badge { Text(cart.sumOf { it.quantity }.toString()) } }) { Icon(Icons.Default.ShoppingCart, "Cart") } } } ) }, bottomBar = { NavigationBar { listOf(ShopTab.Home to Icons.Default.Home, ShopTab.Orders to Icons.Default.ReceiptLong, ShopTab.Cart to Icons.Default.ShoppingCart, ShopTab.Profile to Icons.Default.Person).forEach { (item, icon) -> NavigationBarItem(selected = tab == item, onClick = { tab = item }, icon = { Icon(icon, null) }, label = { Text(item.name) }) } } }, snackbarHost = { SnackbarHost(snackbars) }) { padding -> when (tab) { ShopTab.Home -> HomeScreen(products, query, { query = it }, loading, { selected = it }, Modifier.padding(padding)); ShopTab.Orders -> OrdersScreen(accessToken, Modifier.padding(padding)); ShopTab.Cart -> CartScreen(cart, products, ::updateCart, { scope.launch { runCatching { StoreMeshApi().clearCart(accessToken) }.onSuccess { cart = emptyList() } } }, { showCheckout = true }, false, Modifier.padding(padding)); ShopTab.Profile -> ProfileScreen(onLogout, Modifier.padding(padding)) } }
    }
    selected?.let { product -> ProductDetailsSheet(product, { updateCart(product.id, 1); selected = null }, { selected = null }) }
    if (showCheckout) CheckoutSheet(cart, products, { showCheckout = false }) { val customerId = accessTokenSubject(accessToken); scope.launch { runCatching { StoreMeshApi().createOrder(accessToken, customerId, cart) }.onSuccess { order -> StoreMeshApi().clearCart(accessToken); cart = emptyList(); showCheckout = false; tab = ShopTab.Orders; snackbars.showSnackbar("Order ${order.orderId} placed") }.onFailure { snackbars.showSnackbar(it.message ?: "Checkout failed") } } }
}

@Composable private fun HomeScreen(products: List<Product>, query: String, onQuery: (String) -> Unit, loading: Boolean, onSelect: (Product) -> Unit, modifier: Modifier) { Column(modifier.fillMaxSize()) { OutlinedTextField(query, onQuery, Modifier.fillMaxWidth().padding(horizontal = 16.dp, vertical = 8.dp), placeholder = { Text("Search products") }, leadingIcon = { Icon(Icons.Default.Search, null) }, singleLine = true, shape = RoundedCornerShape(16.dp)); if (loading) Box(Modifier.fillMaxSize(), contentAlignment = Alignment.Center) { CircularProgressIndicator() } else LazyVerticalGrid(GridCells.Adaptive(160.dp), contentPadding = PaddingValues(16.dp), horizontalArrangement = Arrangement.spacedBy(12.dp), verticalArrangement = Arrangement.spacedBy(16.dp)) { item(span = { GridItemSpan(maxLineSpan) }) { DealBanner() }; item(span = { GridItemSpan(maxLineSpan) }) { Text("Featured products", style = MaterialTheme.typography.titleLarge, fontWeight = FontWeight.Bold) }; items(products.filter { query.isBlank() || it.name.contains(query, true) || it.description.contains(query, true) }) { ProductCard(it, onSelect) } } } }
@Composable private fun DealBanner() { Card(colors = CardDefaults.cardColors(containerColor = Color(0xFFDDF7E9)), shape = RoundedCornerShape(20.dp), modifier = Modifier.fillMaxWidth()) { Row(Modifier.padding(18.dp), verticalAlignment = Alignment.CenterVertically) { Column(Modifier.weight(1f)) { Text("Summer deals", style = MaterialTheme.typography.titleLarge, fontWeight = FontWeight.Bold, color = Color(0xFF075E3B)); Text("Up to 30% off selected products", color = Color(0xFF176B4B)); Button(onClick = {}, modifier = Modifier.padding(top = 10.dp)) { Text("Shop now") } }; Icon(Icons.Default.LocalOffer, null, tint = Color(0xFFF59E0B), modifier = Modifier.size(54.dp)) } } }
@Composable private fun ProductCard(product: Product, onClick: (Product) -> Unit) { Card(onClick = { onClick(product) }, shape = RoundedCornerShape(18.dp)) { Column(Modifier.padding(12.dp)) { ProductArtwork(product, 112.dp); Spacer(Modifier.height(8.dp)); Text(product.name, fontWeight = FontWeight.Bold, maxLines = 2); Text(product.description, color = MaterialTheme.colorScheme.onSurfaceVariant, maxLines = 2, style = MaterialTheme.typography.bodySmall); Spacer(Modifier.height(4.dp)); Text(product.formattedPrice(), color = Color(0xFF087443), fontWeight = FontWeight.Bold) } } }
private fun artworkAsset(product: Product): String = when {
    product.sku?.startsWith("SM-LAMP") == true || product.sku?.startsWith("SM-LITE") == true -> "halo-desk-lamp"
    product.sku?.startsWith("SM-MUG") == true || product.sku?.startsWith("SM-COFF") == true || product.sku?.startsWith("SM-TEA") == true -> "cove-ceramic-mug"
    product.sku?.startsWith("SM-CHRG") == true || product.sku?.startsWith("SM-KEYB") == true || product.sku?.startsWith("SM-CABL") == true || product.sku?.startsWith("SM-HUB") == true || product.sku?.startsWith("SM-STND") == true -> "arc-wireless-charger"
    product.sku?.startsWith("SM-THRW") == true || product.sku?.startsWith("SM-SHTS") == true -> "cloud-wool-throw"
    product.sku?.startsWith("SM-TOTE") == true -> "canvas-market-tote"
    product.sku?.startsWith("SM-BACK") == true -> "studio-backpack"
    product.sku?.startsWith("SM-WLET") == true -> "common-leather-wallet"
    product.sku?.startsWith("SM-UMBR") == true -> "rain-travel-umbrella"
    product.sku?.startsWith("SM-SPKR") == true -> "lumen-portable-speaker"
    product.sku?.startsWith("SM-HEAD") == true -> "ridge-headphones"
    product.sku?.startsWith("SM-POT") == true -> "moss-plant-pot"
    product.sku?.startsWith("SM-CNDL") == true -> "hearth-candle"
    product.sku?.startsWith("SM-VASE") == true -> "north-ceramic-vase"
    product.sku?.startsWith("SM-BASK") == true -> "woven-storage-basket"
    else -> "halo-desk-lamp"
}

@Composable private fun ProductArtwork(product: Product, height: androidx.compose.ui.unit.Dp) { val asset = artworkAsset(product); val imagePath = "file:///android_asset/catalog/$asset.png"; var failed by remember(asset) { mutableStateOf(false) }; Box(Modifier.fillMaxWidth().height(height).clip(RoundedCornerShape(14.dp)).background(Color(0xFFE8F0FF)), contentAlignment = Alignment.Center) { AsyncImage(model = imagePath, contentDescription = product.name, modifier = Modifier.fillMaxSize().padding(6.dp), contentScale = androidx.compose.ui.layout.ContentScale.Fit, onError = { failed = true }); if (failed) Icon(Icons.Default.Inventory2, null, tint = MaterialTheme.colorScheme.primary, modifier = Modifier.size(46.dp)) } }
@OptIn(ExperimentalMaterial3Api::class)
@Composable private fun ProductDetailsSheet(product: Product, onAdd: () -> Unit, onDismiss: () -> Unit) { ModalBottomSheet(onDismissRequest = onDismiss) { Column(Modifier.padding(24.dp).padding(bottom = 24.dp)) { ProductArtwork(product, 220.dp); Text(product.name, style = MaterialTheme.typography.headlineSmall, fontWeight = FontWeight.Bold, modifier = Modifier.padding(top = 18.dp)); Text(product.formattedPrice(), style = MaterialTheme.typography.titleLarge, color = Color(0xFF087443), fontWeight = FontWeight.Bold); Text(product.description, modifier = Modifier.padding(vertical = 12.dp), color = MaterialTheme.colorScheme.onSurfaceVariant); Button(onClick = onAdd, modifier = Modifier.fillMaxWidth()) { Text("Add to cart") } } } }
@Composable private fun ProfileScreen(onLogout: () -> Unit, modifier: Modifier) { Column(modifier.fillMaxSize().padding(20.dp)) { Text("Profile", style = MaterialTheme.typography.headlineMedium, fontWeight = FontWeight.Bold); Card(Modifier.fillMaxWidth().padding(top = 16.dp)) { Column(Modifier.padding(18.dp)) { Icon(Icons.Default.AccountCircle, null, modifier = Modifier.size(56.dp), tint = MaterialTheme.colorScheme.primary); Text("Customer account", style = MaterialTheme.typography.titleLarge, fontWeight = FontWeight.Bold); Text("Manage your account, addresses, and payment methods", color = MaterialTheme.colorScheme.onSurfaceVariant) } }; listOf("My details", "Addresses", "Payment methods", "Notifications", "Help & support", "Settings").forEach { label -> ListItem(headlineContent = { Text(label) }, leadingContent = { Icon(Icons.Default.ChevronRight, null) }) }; TextButton(onClick = onLogout) { Text("Sign out", color = MaterialTheme.colorScheme.error) } } }
@Composable private fun OrdersScreen(token: String, modifier: Modifier = Modifier) { var orders by remember { mutableStateOf<List<Order>>(emptyList()) }; LaunchedEffect(token) { runCatching { StoreMeshApi().orders(token) }.onSuccess { orders = it } }; if (orders.isEmpty()) Box(modifier.fillMaxSize(), contentAlignment = Alignment.Center) { Column(horizontalAlignment = Alignment.CenterHorizontally) { Icon(Icons.Default.Inventory2, null, modifier = Modifier.size(64.dp), tint = MaterialTheme.colorScheme.primary); Text("No orders yet", style = MaterialTheme.typography.titleLarge, fontWeight = FontWeight.Bold); Text("Your placed orders will appear here.", color = MaterialTheme.colorScheme.onSurfaceVariant) } } else LazyColumn(modifier.fillMaxSize().padding(20.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) { items(orders.size) { index -> val order = orders[index]; Card(Modifier.fillMaxWidth()) { ListItem(headlineContent = { Text(order.orderId, fontWeight = FontWeight.Bold) }, supportingContent = { Text(order.status.removePrefix("ORDER_STATUS_").lowercase().replaceFirstChar { it.uppercase() }) }, trailingContent = { Text("${order.currency} ${"%.2f".format(order.totalMinor / 100.0)}") }) } } } }
@OptIn(ExperimentalMaterial3Api::class)
@Composable private fun CheckoutSheet(lines: List<CartLine>, products: List<Product>, onDismiss: () -> Unit, onPlaceOrder: () -> Unit) { ModalBottomSheet(onDismissRequest = onDismiss) { Column(Modifier.padding(24.dp).padding(bottom = 24.dp)) { Text("Checkout", style = MaterialTheme.typography.headlineSmall, fontWeight = FontWeight.Bold); Text("Delivery address", style = MaterialTheme.typography.titleMedium, modifier = Modifier.padding(top = 18.dp)); Card(Modifier.fillMaxWidth().padding(top = 8.dp)) { Text("Nairobi, Kenya\nStandard delivery · 2–3 business days", Modifier.padding(16.dp)) }; val total = lines.sumOf { line -> products.firstOrNull { it.id == line.productId }?.priceMinor?.times(line.quantity.toLong()) ?: 0L }; Row(Modifier.fillMaxWidth().padding(vertical = 20.dp), horizontalArrangement = Arrangement.SpaceBetween) { Text("Total", fontWeight = FontWeight.Bold); Text("USD ${"%.2f".format(total / 100.0)}", fontWeight = FontWeight.Bold, color = Color(0xFF087443)) }; Button(onClick = onPlaceOrder, modifier = Modifier.fillMaxWidth(), enabled = lines.isNotEmpty()) { Text("Place order") } } } }
